// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: zerrors/zerrors.proto

package zerrors

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 未知错误，服务器内部错误
	ErrorReason_Unknown ErrorReason = 0
	// 无效参数错误
	ErrorReason_InvalidParameter ErrorReason = 1
	// 未找到错误
	ErrorReason_NotFound ErrorReason = 2
	// 未经授权错误
	ErrorReason_Unauthorized ErrorReason = 3
	// 禁止访问错误
	ErrorReason_Forbidden ErrorReason = 4
	// 缺少幂等性令牌错误
	ErrorReason_IdempotentMissingToken ErrorReason = 5
	// 幂等性令牌已过期错误
	ErrorReason_IdepotentTokenExpired ErrorReason = 6
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "Unknown",
		1: "InvalidParameter",
		2: "NotFound",
		3: "Unauthorized",
		4: "Forbidden",
		5: "IdempotentMissingToken",
		6: "IdepotentTokenExpired",
	}
	ErrorReason_value = map[string]int32{
		"Unknown":                0,
		"InvalidParameter":       1,
		"NotFound":               2,
		"Unauthorized":           3,
		"Forbidden":              4,
		"IdempotentMissingToken": 5,
		"IdepotentTokenExpired":  6,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_zerrors_zerrors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_zerrors_zerrors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_zerrors_zerrors_proto_rawDescGZIP(), []int{0}
}

var File_zerrors_zerrors_proto protoreflect.FileDescriptor

const file_zerrors_zerrors_proto_rawDesc = "" +
	"\n" +
	"\x15zerrors/zerrors.proto\x12\azerrors\x1a\x13errors/errors.proto*\xc6\x01\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUnknown\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x1a\n" +
	"\x10InvalidParameter\x10\x01\x1a\x04\xa8E\x90\x03\x12\x12\n" +
	"\bNotFound\x10\x02\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUnauthorized\x10\x03\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tForbidden\x10\x04\x1a\x04\xa8E\x93\x03\x12 \n" +
	"\x16IdempotentMissingToken\x10\x05\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x15IdepotentTokenExpired\x10\x06\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03B9Z7github.com/fleezesd/xnightwatch/pkg/api/zerrors;zerrorsb\x06proto3"

var (
	file_zerrors_zerrors_proto_rawDescOnce sync.Once
	file_zerrors_zerrors_proto_rawDescData []byte
)

func file_zerrors_zerrors_proto_rawDescGZIP() []byte {
	file_zerrors_zerrors_proto_rawDescOnce.Do(func() {
		file_zerrors_zerrors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerrors_zerrors_proto_rawDesc), len(file_zerrors_zerrors_proto_rawDesc)))
	})
	return file_zerrors_zerrors_proto_rawDescData
}

var file_zerrors_zerrors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zerrors_zerrors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: zerrors.ErrorReason
}
var file_zerrors_zerrors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zerrors_zerrors_proto_init() }
func file_zerrors_zerrors_proto_init() {
	if File_zerrors_zerrors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerrors_zerrors_proto_rawDesc), len(file_zerrors_zerrors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerrors_zerrors_proto_goTypes,
		DependencyIndexes: file_zerrors_zerrors_proto_depIdxs,
		EnumInfos:         file_zerrors_zerrors_proto_enumTypes,
	}.Build()
	File_zerrors_zerrors_proto = out.File
	file_zerrors_zerrors_proto_goTypes = nil
	file_zerrors_zerrors_proto_depIdxs = nil
}
