// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: gateway/v1/gateway.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitVersion    string                 `protobuf:"bytes,1,opt,name=GitVersion,proto3" json:"GitVersion,omitempty"`
	GitCommit     string                 `protobuf:"bytes,2,opt,name=GitCommit,proto3" json:"GitCommit,omitempty"`
	GitTreeState  string                 `protobuf:"bytes,3,opt,name=GitTreeState,proto3" json:"GitTreeState,omitempty"`
	BuildDate     string                 `protobuf:"bytes,4,opt,name=BuildDate,proto3" json:"BuildDate,omitempty"`
	GoVersion     string                 `protobuf:"bytes,5,opt,name=GoVersion,proto3" json:"GoVersion,omitempty"`
	Compiler      string                 `protobuf:"bytes,6,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=Platform,proto3" json:"Platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetVersionResponse) GetGitVersion() string {
	if x != nil {
		return x.GitVersion
	}
	return ""
}

func (x *GetVersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *GetVersionResponse) GetGitTreeState() string {
	if x != nil {
		return x.GitTreeState
	}
	return ""
}

func (x *GetVersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetVersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *GetVersionResponse) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *GetVersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\x0eapi.gateway.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xea\x01\n" +
	"\x12GetVersionResponse\x12\x1e\n" +
	"\n" +
	"GitVersion\x18\x01 \x01(\tR\n" +
	"GitVersion\x12\x1c\n" +
	"\tGitCommit\x18\x02 \x01(\tR\tGitCommit\x12\"\n" +
	"\fGitTreeState\x18\x03 \x01(\tR\fGitTreeState\x12\x1c\n" +
	"\tBuildDate\x18\x04 \x01(\tR\tBuildDate\x12\x1c\n" +
	"\tGoVersion\x18\x05 \x01(\tR\tGoVersion\x12\x1a\n" +
	"\bCompiler\x18\x06 \x01(\tR\bCompiler\x12\x1a\n" +
	"\bPlatform\x18\a \x01(\tR\bPlatform2e\n" +
	"\aGateway\x12Z\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\".api.gateway.v1.GetVersionResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/versionBE\n" +
	"\x0eapi.gateway.v1P\x01Z1github.com/fleezesd/xnightwatch/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*GetVersionResponse)(nil), // 0: api.gateway.v1.GetVersionResponse
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	1, // 0: api.gateway.v1.Gateway.GetVersion:input_type -> google.protobuf.Empty
	0, // 1: api.gateway.v1.Gateway.GetVersion:output_type -> api.gateway.v1.GetVersionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
