// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: gateway/v1/gateway.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitVersion    string                 `protobuf:"bytes,1,opt,name=GitVersion,proto3" json:"GitVersion,omitempty"`
	GitCommit     string                 `protobuf:"bytes,2,opt,name=GitCommit,proto3" json:"GitCommit,omitempty"`
	GitTreeState  string                 `protobuf:"bytes,3,opt,name=GitTreeState,proto3" json:"GitTreeState,omitempty"`
	BuildDate     string                 `protobuf:"bytes,4,opt,name=BuildDate,proto3" json:"BuildDate,omitempty"`
	GoVersion     string                 `protobuf:"bytes,5,opt,name=GoVersion,proto3" json:"GoVersion,omitempty"`
	Compiler      string                 `protobuf:"bytes,6,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=Platform,proto3" json:"Platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetVersionResponse) GetGitVersion() string {
	if x != nil {
		return x.GitVersion
	}
	return ""
}

func (x *GetVersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *GetVersionResponse) GetGitTreeState() string {
	if x != nil {
		return x.GitTreeState
	}
	return ""
}

func (x *GetVersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetVersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *GetVersionResponse) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *GetVersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type MinerSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	DeletePolicy  string                 `protobuf:"bytes,4,opt,name=deletePolicy,proto3" json:"deletePolicy,omitempty"`
	MinerTemplate *MinerTemplate         `protobuf:"bytes,5,opt,name=MinerTemplate,proto3" json:"MinerTemplate,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinerSet) Reset() {
	*x = MinerSet{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerSet) ProtoMessage() {}

func (x *MinerSet) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerSet.ProtoReflect.Descriptor instead.
func (*MinerSet) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *MinerSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MinerSet) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *MinerSet) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MinerSet) GetDeletePolicy() string {
	if x != nil {
		return x.DeletePolicy
	}
	return ""
}

func (x *MinerSet) GetMinerTemplate() *MinerTemplate {
	if x != nil {
		return x.MinerTemplate
	}
	return nil
}

func (x *MinerSet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MinerSet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MinerTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinerType     string                 `protobuf:"bytes,1,opt,name=minerType,proto3" json:"minerType,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chainName,proto3" json:"chainName,omitempty"`
	DataDir       string                 `protobuf:"bytes,3,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinerTemplate) Reset() {
	*x = MinerTemplate{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerTemplate) ProtoMessage() {}

func (x *MinerTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerTemplate.ProtoReflect.Descriptor instead.
func (*MinerTemplate) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *MinerTemplate) GetMinerType() string {
	if x != nil {
		return x.MinerType
	}
	return ""
}

func (x *MinerTemplate) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *MinerTemplate) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

type ListMinerSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerSetRequest) Reset() {
	*x = ListMinerSetRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerSetRequest) ProtoMessage() {}

func (x *ListMinerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerSetRequest.ProtoReflect.Descriptor instead.
func (*ListMinerSetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ListMinerSetRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMinerSetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMinerSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	MinerSets     []*MinerSet            `protobuf:"bytes,2,rep,name=MinerSets,proto3" json:"MinerSets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerSetResponse) Reset() {
	*x = ListMinerSetResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerSetResponse) ProtoMessage() {}

func (x *ListMinerSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerSetResponse.ProtoReflect.Descriptor instead.
func (*ListMinerSetResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ListMinerSetResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMinerSetResponse) GetMinerSets() []*MinerSet {
	if x != nil {
		return x.MinerSets
	}
	return nil
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\x0eapi.gateway.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xea\x01\n" +
	"\x12GetVersionResponse\x12\x1e\n" +
	"\n" +
	"GitVersion\x18\x01 \x01(\tR\n" +
	"GitVersion\x12\x1c\n" +
	"\tGitCommit\x18\x02 \x01(\tR\tGitCommit\x12\"\n" +
	"\fGitTreeState\x18\x03 \x01(\tR\fGitTreeState\x12\x1c\n" +
	"\tBuildDate\x18\x04 \x01(\tR\tBuildDate\x12\x1c\n" +
	"\tGoVersion\x18\x05 \x01(\tR\tGoVersion\x12\x1a\n" +
	"\bCompiler\x18\x06 \x01(\tR\bCompiler\x12\x1a\n" +
	"\bPlatform\x18\a \x01(\tR\bPlatform\"\xb9\x02\n" +
	"\bMinerSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\x12 \n" +
	"\vdisplayName\x18\x03 \x01(\tR\vdisplayName\x12\"\n" +
	"\fdeletePolicy\x18\x04 \x01(\tR\fdeletePolicy\x12C\n" +
	"\rMinerTemplate\x18\x05 \x01(\v2\x1d.api.gateway.v1.MinerTemplateR\rMinerTemplate\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"e\n" +
	"\rMinerTemplate\x12\x1c\n" +
	"\tminerType\x18\x01 \x01(\tR\tminerType\x12\x1c\n" +
	"\tchainName\x18\x02 \x01(\tR\tchainName\x12\x18\n" +
	"\adataDir\x18\x03 \x01(\tR\adataDir\"C\n" +
	"\x13ListMinerSetRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"n\n" +
	"\x14ListMinerSetResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x126\n" +
	"\tMinerSets\x18\x02 \x03(\v2\x18.api.gateway.v1.MinerSetR\tMinerSets2\x89\x03\n" +
	"\aGateway\x12Z\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\".api.gateway.v1.GetVersionResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/version\x12p\n" +
	"\fListMinerSet\x12#.api.gateway.v1.ListMinerSetRequest\x1a$.api.gateway.v1.ListMinerSetResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/minersets\x12Z\n" +
	"\x0eCreateMinerSet\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/minersets\x12T\n" +
	"\vCreateMiner\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/minersBE\n" +
	"\x0eapi.gateway.v1P\x01Z1github.com/fleezesd/xnightwatch/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*GetVersionResponse)(nil),    // 0: api.gateway.v1.GetVersionResponse
	(*MinerSet)(nil),              // 1: api.gateway.v1.MinerSet
	(*MinerTemplate)(nil),         // 2: api.gateway.v1.MinerTemplate
	(*ListMinerSetRequest)(nil),   // 3: api.gateway.v1.ListMinerSetRequest
	(*ListMinerSetResponse)(nil),  // 4: api.gateway.v1.ListMinerSetResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	2, // 0: api.gateway.v1.MinerSet.MinerTemplate:type_name -> api.gateway.v1.MinerTemplate
	5, // 1: api.gateway.v1.MinerSet.createdAt:type_name -> google.protobuf.Timestamp
	5, // 2: api.gateway.v1.MinerSet.updatedAt:type_name -> google.protobuf.Timestamp
	1, // 3: api.gateway.v1.ListMinerSetResponse.MinerSets:type_name -> api.gateway.v1.MinerSet
	6, // 4: api.gateway.v1.Gateway.GetVersion:input_type -> google.protobuf.Empty
	3, // 5: api.gateway.v1.Gateway.ListMinerSet:input_type -> api.gateway.v1.ListMinerSetRequest
	6, // 6: api.gateway.v1.Gateway.CreateMinerSet:input_type -> google.protobuf.Empty
	6, // 7: api.gateway.v1.Gateway.CreateMiner:input_type -> google.protobuf.Empty
	0, // 8: api.gateway.v1.Gateway.GetVersion:output_type -> api.gateway.v1.GetVersionResponse
	4, // 9: api.gateway.v1.Gateway.ListMinerSet:output_type -> api.gateway.v1.ListMinerSetResponse
	6, // 10: api.gateway.v1.Gateway.CreateMinerSet:output_type -> google.protobuf.Empty
	6, // 11: api.gateway.v1.Gateway.CreateMiner:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
