// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/fleezesd/xnightwatch/internal/gateway/store"
	"github.com/fleezesd/xnightwatch/pkg/db"
)

import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

// Injectors from wire.go:

func wireStoreClient(mysqlOptions *db.MySQLOptions) (store.IStore, error) {
	gormDB, err := db.NewMySQL(mysqlOptions)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(gormDB)
	return datastore, nil
}
