// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package nightwatch

import (
	store2 "github.com/fleezesd/xnightwatch/internal/gateway/store"
	"github.com/fleezesd/xnightwatch/internal/pkg/client/store"
	store3 "github.com/fleezesd/xnightwatch/internal/usercenter/store"
	"github.com/fleezesd/xnightwatch/pkg/db"
)

import (
	_ "github.com/fleezesd/xnightwatch/internal/nightwatch/watcher/all"
)

// Injectors from wire.go:

func wireStoreClient(mySQLOptions *db.MySQLOptions) (store.Interface, error) {
	gormDB, err := db.NewMySQL(mySQLOptions)
	if err != nil {
		return nil, err
	}
	datastore := store2.NewStore(gormDB)
	storeDatastore := store3.NewStore(gormDB)
	datastore2 := store.NewStore(datastore, storeDatastore)
	return datastore2, nil
}
